In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/crop_data.csv")
df

      Crops  Distance  Prices               Names
0     Wheat        18      32      Adalie Allcott
1    Rubber       640      13         Kieth Clark
2    Rubber       230      13         Emely Swift
3    Rubber       636      10       Ethan Addison
4     Maize       179     106         Eryn Brooks
..      ...       ...     ...                 ...
495  Barley        20      66      Marina Pickard
496  Barley       722      63  Savannah Greenwood
497   Wheat       255      38    Phillip Matthews
498   Maize       282     109        Olivia Ranks
499  Barley       170      60          Rae Cooper

[500 rows x 4 columns]

## Score
score=sqrt((A1x(distance-customer_distance))^2 + (A2xprices)^2)   //SomeFunction

Current A1=0.7
        A2=0.2

In [ ]:
def find_score(distance,cust_distance,price):
    distance_score=0.7*(distance-cust_distance)**2
    price_score=(0.2*price)**2
    score=(distance_score+price_score)**0.5
    return score

In [ ]:
def find_min_score(df,crop_name,cust_distance):
    df_crop=df[df.Crops==crop_name]
    df_score=find_score(df_crop.Distance,cust_distance,df_crop.Prices)
    print(df_score)
    # print(cust_distance)
    return df_score

In [ ]:
df_score=find_min_score(df,"Wheat",np.random.randint(0,1000))
# print(df_score)
min_ind=df_score.idxmin()
Ideal_Seller=df.loc[min_ind].Names
print("The Recommended Seller is: "+Ideal_Seller)


# print(df_score.min())

0      344.763339
8      170.814051
11     236.060501
13     114.039291
20      39.941207
          ...
480     97.290493
481    192.559082
484    117.341382
489    248.598190
497    146.612619
Length: 100, dtype: float64
The Recommended Seller is: Mackenzie Lewis

In [ ]:
# df_score.loc[289]

6.5038450166036395

In [ ]:
# df.loc[289]

Crops       Wheat
Distance      680
Prices         30
Name: 289, dtype: object


## Crops Recommended Price Predictor

Used Predictor <br>
Mean<br>
Can probably replace with something better

In [ ]:
def Predict_Price_formula(arr):
  return arr.mean()

In [ ]:
def Predict_Price(df,crop_name):
  df_crop=df[df.Crops==crop_name]
  return Predict_Price_formula(df_crop.tail(20).Prices)

In [ ]:
print("The Recommended price for wheat is "+ str(Predict_Price(df,"Barley")));

The Recommended price for wheat is 64.6